export const DEFAULT_TRANSLATION_TIMEOUT_MS = 10_000;
export const DEFAULT_TRANSLATION_MAX_CONCURRENT = 5;
export const DEFAULT_MAX_TRANSLATION_INPUT_LENGTH = 2000;
export const DEFAULT_MAX_TRANSLATION_OUTPUT_LENGTH = 4000;
export const DEFAULT_TRANSLATION_DEDUPE_TTL_SEC = 300;
export const DEFAULT_TRANSLATION_COOLDOWN_TTL_SEC = 3;
export const DEFAULT_TRANSLATION_SLASH_DEDUPE_TTL_SEC = 30;
export const DEFAULT_CACHE_MAX_ENTRIES = 10_000;
